### ISSUE TITLE
Narrow version support (due to competing gem problems)

### ISSUE THREAD

**Issue by tokengeek** [rubiojr/knife-brightbox#20]
So this is a general question for users.

I just tried to bundle with Ruby 2.2 and hit an issue with `json-v1.7.7` failing to build (https://github.com/flori/json/issues/229)

In an attempt to dodge that I tried updating `chef` (which set the json limits) which then installed a `mixlib-shellout` which required >= 1.9.3

Which version of Ruby do folks use with `knife-brightbox` so I can find the correct balance?

/cc @gregkare @kangguru @rubiojr

**Comment by kangguru** [comment]
ruby 2.2.0 and chef 12.0.3, works like a charm

**Comment by tokengeek** [comment]
@kangguru Yep.

However it looks like updating to `chef-v12...` drops 1.8.7 support (without me specifying a lot of alternative versions perhaps).

I'm happy for that to happen just wanted to make sure that doesn't screw up anyone's workflow.

I'll update the gemspec and version to cut a major release if that's okay.

I'll probably release the current master as well first, just wanted to make things clearer for users if possible.

**Comment by gregkare** [comment]
We're using Ruby 2.1 and Chef 11 at the moment on our development machines

**Comment by tokengeek** [comment]
Okay. I won't rush to do this. The current dependencies are so loose that it looks like an update date system doesn't see this problem.

It probably affects me doing `bundle install` on my old `1.8` install. My `1.9` and `2.2` are fine with it as it is.

I'll close and wait until we break it all with `fog 2.0` :smile:
